Writable:
  LogLevel: DEBUG

Service:
  Port: 59999
  StartupMsg: Example bitfields device service started

Clients:
  core-metadata:
    Host: localhost
    Port: 59881

Device:
  ProfilesDir: ./res/profiles
  DevicesDir: ./res/devices

MessageBus:
  Protocol: redis
  Host: localhost
  Port: 6379
  Type: redis
  AuthMode: usernamepassword
  SecretName: redisdb
  Optional:
    ClientId: device-bitfields
