allowMergeCommits: true
# Always validate the PR title AND all the commits
titleAndCommits: true
types:
    - feat
    - fix
    - docs
    - examples
    - style
    - refactor
    - perf
    - test
    - build
    - ci
    - revert
